In [19]:
import numpy as np

In [20]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a[1,5]

np.int64(13)

In [22]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
a[:,2]

array([ 3, 10])

In [28]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [29]:
print(b[0,1,1])

4


In [30]:
b(:,1,:)


SyntaxError: invalid syntax (3912226327.py, line 1)

In [31]:
b[:,1,:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])